DROP TYPE IF EXISTS "user_role";
CREATE TYPE "user_role" AS ENUM ('ADMIN', 'USER');

DROP TABLE IF EXISTS "users";
CREATE TABLE "users" (
   "id" BIGSERIAL PRIMARY KEY,
   "username" VARCHAR(255) NOT NULL,
   "password" VARCHAR(255) NOT NULL,
   "role" "user_role" NOT NULL DEFAULT 'USER',
   "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   UNIQUE ("username")
);